// <auto-generated />
using System;
using EcoRoute.Supports.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoRoute.Settings.Migrations
{
    [DbContext(typeof(SettingsContext))]
    partial class SettingsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoRoute.Settings.Entities.Avatar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Avatars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcd3c63f-48c4-4d31-a416-0c9b969b60dd"),
                            Name = "Avatar 1",
                            Url = "https://api.dicebear.com/9.x/adventurer/svg?seed=Luis"
                        },
                        new
                        {
                            Id = new Guid("25e28709-b062-4ccf-8f4a-a3f0e1c8035a"),
                            Name = "Avatar 2",
                            Url = "https://api.dicebear.com/9.x/adventurer/svg?seed=Avery"
                        },
                        new
                        {
                            Id = new Guid("5f9fe6f1-a0d0-49be-ad79-f3164841a31f"),
                            Name = "Avatar 3",
                            Url = "https://api.dicebear.com/9.x/adventurer/svg?seed=Jude"
                        },
                        new
                        {
                            Id = new Guid("925370be-4902-48b9-a3ea-8ae41ca19232"),
                            Name = "Avatar 4",
                            Url = "https://api.dicebear.com/9.x/adventurer/svg?seed=Jack"
                        },
                        new
                        {
                            Id = new Guid("e6898c3d-b58e-4da5-9114-7cb6c76cf790"),
                            Name = "Avatar 5",
                            Url = "https://api.dicebear.com/9.x/adventurer/svg?seed=Jocelyn"
                        },
                        new
                        {
                            Id = new Guid("ab7890a6-0e94-4dc7-8a3f-74f85f80353d"),
                            Name = "Avatar 6",
                            Url = "https://api.dicebear.com/9.x/adventurer/svg?seed=Easton"
                        });
                });

            modelBuilder.Entity("EcoRoute.Settings.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableAnimations")
                        .HasColumnType("bit");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("GoogleMapsApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae0443f1-917c-44db-9ecb-265f03c5b4ed"),
                            AvatarUrl = "https://api.dicebear.com/9.x/adventurer/svg?seed=Easton",
                            DarkMode = false,
                            EmailNotifications = true,
                            EnableAnimations = true,
                            FontSize = 14,
                            GoogleMapsApiKey = "",
                            PushNotifications = true,
                            SmsNotifications = false,
                            ThemeColor = "#2ba86d"
                        });
                });

            modelBuilder.Entity("EcoRoute.Settings.Entities.ThemeColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThemeColors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d356529-28bb-45bb-80b5-b25da1073d6e"),
                            Name = "Orijinal",
                            Value = "#2ba86d"
                        },
                        new
                        {
                            Id = new Guid("d3aefb83-49b3-4497-835b-919b5754cebe"),
                            Name = "Mavi",
                            Value = "#3B82F6"
                        },
                        new
                        {
                            Id = new Guid("5408af70-b683-4c54-83ef-e7cec5c3d18a"),
                            Name = "Kırmızı",
                            Value = "#EF4444"
                        },
                        new
                        {
                            Id = new Guid("11b56dde-e8e5-4e87-b43b-4c58acf8b996"),
                            Name = "Mor",
                            Value = "#8B5CF6"
                        },
                        new
                        {
                            Id = new Guid("04a59f81-2372-413b-8760-2150acdeba1e"),
                            Name = "Pembe",
                            Value = "#EC4899"
                        },
                        new
                        {
                            Id = new Guid("c7a4da28-f770-478d-8ae0-84563fa558ea"),
                            Name = "Sarı",
                            Value = "#F59E0B"
                        },
                        new
                        {
                            Id = new Guid("7f5c0536-f408-4f83-b19d-a76892df23ea"),
                            Name = "Turkuaz",
                            Value = "#06B6D4"
                        },
                        new
                        {
                            Id = new Guid("1dccb679-b3b3-4039-be89-58259c01df5e"),
                            Name = "Indigo",
                            Value = "#6366F1"
                        },
                        new
                        {
                            Id = new Guid("fef03528-4ac0-49a6-adca-7ad7888dcd6a"),
                            Name = "Lime",
                            Value = "#84CC16"
                        },
                        new
                        {
                            Id = new Guid("f649b485-4de1-4197-9212-b077cd729789"),
                            Name = "Gri",
                            Value = "#6B7280"
                        },
                        new
                        {
                            Id = new Guid("fac9cdaf-beeb-49a4-9efb-84395499096b"),
                            Name = "Turuncu",
                            Value = "#F97316"
                        },
                        new
                        {
                            Id = new Guid("fa62d005-3ad7-4919-a2c2-e3f058405160"),
                            Name = "Teal",
                            Value = "#14B8A6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
